### ISSUE TITLE
程序放在网站下下载目录时，从下一目录无法返回下载目录

### ISSUE THREAD

**Issue by baoang** [ToyoDAdoubi/DirectoryLister#5]
如网站是domain.tld，现下载目录路径是domain.tld/download。
在下载目录内，分几个子目录，分别是soft、doc、photo，即构成
domain.tld/download/soft
domain.tld/download/doc
domain.tld/download/photo
现在将逗比魔改版上传到download目录下，解压后大体是这样：
domain.tld/download/soft
domain.tld/download/doc
domain.tld/download/photo
domain.tld/resources
domain.tld/index.php

正常情况下希望访客进入到download/soft这个目录下之后，能通过点击文件列表顶端向上箭头返回download目录，再次点击文件列表顶端向上箭头则返回网站首页，即domain.tld。
但现在的情况是在download/soft目录下点文件列表顶部向上箭头返回的是网站根目录，即domain.tld。

看了下站长的说明文件，有一处涉及到的是将theme/bootstrap下的index.php的第五行修改为域名后缀，在本例中，应当是修改为tld，但是尝试了一下似乎没有起作用。

请问例如这样的情况，如何修改以使得返回箭头起效？

---
找到同样的问题了，应当是nginx服务器配置的pathinfo导致的
https://github.com/DirectoryLister/DirectoryLister/issues/178

**Comment by ToyoDAdoubi** [comment]
关于子目录的问题，似乎DirectoryLister原版就是这样，很早就见到有人说过了。。
index.php修改域名后缀的只是用来正确显示 README.html 用的。

**Comment by baoang** [comment]
@ToyoDAdoubi 多谢回复！
原来如此。
本以为能找到个极方便的显示目录用的工具，因为fancyindex没有默认编译进nginx中去，找了段时间，在空机器上测试DirLister时发现挺好用，没料到中文显示和pathinfo很麻烦，DL的原作者不知后期会不会有进一步的打磨。
另外，魔改版里bootstrap目录下的index.php里，连接css和js的你用了绝对路径，`/resources/...`的这样，好象用相对路径要准确些，如果放到子目录下的话

**Comment by ToyoDAdoubi** [comment]
路径问题我改了，把 `/resources/xxxx` 改成 `resources/xxxx` 就能解决程序放在子目录 CSS JS 文件路径错误的问题。
另外我修复 CSS JS 路径做测试的时候，发现返回的向上箭头是正常的呀，比如我的就是回到了 `xxx.xx/ceshi` 路径。

一开始我没仔细看，刚才看的时候发现你给的：
```
在下载目录内，分几个子目录，分别是soft、doc、photo，即构成
domain.tld/download/soft
domain.tld/download/doc
domain.tld/download/photo
现在将逗比魔改版上传到download目录下，解压后大体是这样：
domain.tld/download/soft
domain.tld/download/doc
domain.tld/download/photo
domain.tld/resources
domain.tld/index.php
```
你把程序位置放错了，正确的应该是这样：
```
domain.tld/download/soft
domain.tld/download/doc
domain.tld/download/photo
domain.tld/download/resources
domain.tld/download/index.php
```

**Comment by baoang** [comment]
@ToyoDAdoubi 多谢回复！
