### ISSUE TITLE
不能自适应？

### ISSUE THREAD

**Issue by woytu** [ToyoDAdoubi/DirectoryLister#6]
![gif](https://user-images.githubusercontent.com/30252550/44531689-fa4f6000-a723-11e8-9a5e-cdf49e07d577.gif)

**Comment by ToyoDAdoubi** [comment]
![1](https://user-images.githubusercontent.com/17268345/44535327-4ef6d900-a72c-11e8-85ec-3fcf5aff44bc.gif)
我这里显示正常。

**Comment by ToyoDAdoubi** [comment]
研究了下，解决了你说的问题，你现在可以再去试试（记得 ctrl+f5 强制刷新缓存）。
不过我又发现了新问题，那就是当浏览器高度改变为正好与网页主体持平时，底部结构就会与主体文字重叠。
在移动设备上因为浏览器高度都是固定的，所以不影响，只有在PC浏览器上，调整浏览器高度时才会出现。
情况见下图，研究半天也没办法解决，不过这个问题不是很刺眼，影响不大，暂时先搁置好了。
![2](https://user-images.githubusercontent.com/17268345/44542022-50310180-a73e-11e8-937e-f8a5e9b19c74.gif)

**Comment by woytu** [comment]
还有一个
![image](https://user-images.githubusercontent.com/30252550/45010581-f9320300-b040-11e8-887b-3af00ec93f1f.png)最好是图片自适应

**Comment by ToyoDAdoubi** [comment]
CSS 加上图片自适应了。

**Comment by woytu** [comment]
![screenshot_2018-09-09-09-47-22-046_com tencent mt](https://user-images.githubusercontent.com/30252550/45260360-5dc1d900-b418-11e8-83e9-432a3895a238.png)

**Comment by ToyoDAdoubi** [comment]
前面已经说了，这是已知BUG，我暂时无法解决。

**Comment by ToyoDAdoubi** [comment]
已彻底修复该问题（当网页内容高度接近于窗口高度时，底部 footer 与网页内容重叠的问题）。
